from supermarketscraper.items import SupermarketItem
import datetime
import scrapy
import json

# <nome_subcategoria>?store_id=5676
referer = ['alimentos-basicos/acucares-e-adocantes',
           'alimentos-basicos/arroz',
           'alimentos-basicos/cestas',
           'alimentos-basicos/farinaceos-e-amidos',
           'alimentos-basicos/feijao',
           'alimentos-basicos/graos',
           'alimentos-basicos/massas-secas',
           'alimentos-basicos/oleos-azeites-e-vinagres',
           'alimentos-basicos/ovos',
           'alimentos-basicos/sal',
           'bazar-e-utilidades/chinelos',
           'bebidas/aguas',
           'bebidas/bebidas-vegetais',
           'bebidas/chas-prontos',
           'bebidas/isotonicos-e-energeticos',
           'bebidas/refrigerantes',
           'bebidas/sucos',
           'bebidas-alcoolicas/cervejas',
           'bebidas-alcoolicas/destilados',
           'bebidas-alcoolicas/drinks-prontos',
           'bebidas-alcoolicas/vinhos',
           'biscoitos-e-salgadinhos/amendoins-e-cia',
           'biscoitos-e-salgadinhos/biscoitos-doces',
           'biscoitos-e-salgadinhos/biscoitos-salgados',
           'biscoitos-e-salgadinhos/salgadinhos-e-snacks',
           'carnes-aves-e-peixes/aves',
           'carnes-aves-e-peixes/bovinos',
           'carnes-aves-e-peixes/carnes-especiais',
           'carnes-aves-e-peixes/carnes-secas-salgadas-ou-defumadas',
           'carnes-aves-e-peixes/frutos-do-mar',
           'carnes-aves-e-peixes/linguicas-e-salsichas',
           'carnes-aves-e-peixes/peixes',
           'carnes-aves-e-peixes/suinos',
           'congelados/aperitivos-e-empanados',
           'congelados/hamburgueres',
           'congelados/paes-congelados',
           'congelados/pratos-prontos-congelados',
           'congelados/vegetais-congelados',
           'doces-e-sobremesas/balas-e-gomas',
           'doces-e-sobremesas/chocolates',
           'doces-e-sobremesas/doces-prontos',
           'doces-e-sobremesas/frutas-em-calda',
           'doces-e-sobremesas/ingredientes-culinarios',
           'doces-e-sobremesas/pudins-e-gelatinas',
           'doces-e-sobremesas/sorvetes-e-sobremesas',
           'feira/frutas',
           'feira/legumes',
           'feira/temperos-frescos',
           'feira/verduras',
           'frios-e-laticinios/frios',
           'frios-e-laticinios/laticinios',
           'frios-e-laticinios/massas-frescas',
           'frios-e-laticinios/queijos',
           'higiene-e-cuidados-pessoais/bebe',
           'higiene-e-cuidados-pessoais/cabelo',
           'higiene-e-cuidados-pessoais/corpo',
           'higiene-e-cuidados-pessoais/cuidados-com-a-saude',
           'higiene-e-cuidados-pessoais/higiene',
           'higiene-e-cuidados-pessoais/higiene-bucal',
           'higiene-e-cuidados-pessoais/maos-e-pes',
           'leites-e-iogurtes/iogurte-e-bebida-lactea',
           'leites-e-iogurtes/leites-em-po',
           'leites-e-iogurtes/leites-especiais',
           'leites-e-iogurtes/leites-tradicionais',
           'limpeza/casa-em-geral',
           'limpeza/desodorizadores-e-aromatizantes',
           'limpeza/detergentes-e-desengordurantes',
           'limpeza/inseticidas-e-controle-de-pragas',
           'limpeza/roupas',
           'limpeza/utensilios-de-limpeza',
           'matinais/achocolatados-e-cia',
           'matinais/aveias-e-cereais',
           'matinais/cafes',
           'matinais/chas',
           'matinais/mel-e-geleias',
           'matinais/pastas-e-cremes-doces',
           'matinais/torradas',
           'molhos-condimentos-e-conservas/alimentos-prontos-e-enlatados',
           'molhos-condimentos-e-conservas/conservas',
           'molhos-condimentos-e-conservas/maioneses-e-molhos-diversos',
           'molhos-condimentos-e-conservas/molhos-de-tomate',
           'molhos-condimentos-e-conservas/sopas-e-cremes',
           'molhos-condimentos-e-conservas/temperos-e-caldos',
           'padaria/bolos-e-tortas',
           'padaria/confeitaria',
           'padaria/fermentos',
           'padaria/paes',
           'pet-shop/caes',
           'pet-shop/gatos',
           'pet-shop/passaros-e-peixes',
           'utensilios-para-o-lar/automotivos',
           'utensilios-para-o-lar/churrasco',
           'utensilios-para-o-lar/conveniencias',
           'utensilios-para-o-lar/cozinha',
           'utensilios-para-o-lar/embalagens-e-descartaveis',
           'utensilios-para-o-lar/jardinagem',
           'utensilios-para-o-lar/utensilios-diversos']
categorias = ['alimentos-basicos/category/acucares-e-adocantes',
              'alimentos-basicos/category/arroz',
              'alimentos-basicos/category/cestas',
              'alimentos-basicos/category/farinaceos-e-amidos',
              'alimentos-basicos/category/feijao',
              'alimentos-basicos/category/graos',
              'alimentos-basicos/category/massas-secas',
              'alimentos-basicos/category/oleos-azeites-e-vinagres',
              'alimentos-basicos/category/ovos',
              'alimentos-basicos/category/sal',
              'bazar-e-utilidades/category/chinelos',
              'bebidas/category/aguas',
              'bebidas/category/bebidas-vegetais',
              'bebidas/category/chas-prontos',
              'bebidas/category/isotonicos-e-energeticos',
              'bebidas/category/refrigerantes',
              'bebidas/category/sucos',
              'bebidas-alcoolicas/category/cervejas',
              'bebidas-alcoolicas/category/destilados',
              'bebidas-alcoolicas/category/drinks-prontos',
              'bebidas-alcoolicas/category/vinhos',
              'biscoitos-e-salgadinhos/category/amendoins-e-cia',
              'biscoitos-e-salgadinhos/category/biscoitos-doces',
              'biscoitos-e-salgadinhos/category/biscoitos-salgados',
              'biscoitos-e-salgadinhos/category/salgadinhos-e-snacks',
              'carnes-aves-e-peixes/category/aves',
              'carnes-aves-e-peixes/category/bovinos',
              'carnes-aves-e-peixes/category/carnes-especiais',
              'carnes-aves-e-peixes/category/carnes-secas-salgadas-ou-defumadas',
              'carnes-aves-e-peixes/category/frutos-do-mar',
              'carnes-aves-e-peixes/category/linguicas-e-salsichas',
              'carnes-aves-e-peixes/category/peixes',
              'carnes-aves-e-peixes/category/suinos',
              'congelados/category/aperitivos-e-empanados',
              'congelados/category/hamburgueres',
              'congelados/category/paes-congelados',
              'congelados/category/pratos-prontos-congelados',
              'congelados/category/vegetais-congelados',
              'doces-e-sobremesas/category/balas-e-gomas',
              'doces-e-sobremesas/category/chocolates',
              'doces-e-sobremesas/category/doces-prontos',
              'doces-e-sobremesas/category/frutas-em-calda',
              'doces-e-sobremesas/category/ingredientes-culinarios',
              'doces-e-sobremesas/category/pudins-e-gelatinas',
              'doces-e-sobremesas/category/sorvetes-e-sobremesas',
              'feira/category/frutas',
              'feira/category/legumes',
              'feira/category/temperos-frescos',
              'feira/category/verduras',
              'frios-e-laticinios/category/frios',
              'frios-e-laticinios/category/laticinios',
              'frios-e-laticinios/category/massas-frescas',
              'frios-e-laticinios/category/queijos',
              'higiene-e-cuidados-pessoais/category/bebe',
              'higiene-e-cuidados-pessoais/category/cabelo',
              'higiene-e-cuidados-pessoais/category/corpo',
              'higiene-e-cuidados-pessoais/category/cuidados-com-a-saude',
              'higiene-e-cuidados-pessoais/category/higiene',
              'higiene-e-cuidados-pessoais/category/higiene-bucal',
              'higiene-e-cuidados-pessoais/category/maos-e-pes',
              'leites-e-iogurtes/category/iogurte-e-bebida-lactea',
              'leites-e-iogurtes/category/leites-em-po',
              'leites-e-iogurtes/category/leites-especiais',
              'leites-e-iogurtes/category/leites-tradicionais',
              'limpeza/category/casa-em-geral',
              'limpeza/category/desodorizadores-e-aromatizantes',
              'limpeza/category/detergentes-e-desengordurantes',
              'limpeza/category/inseticidas-e-controle-de-pragas',
              'limpeza/category/roupas',
              'limpeza/category/utensilios-de-limpeza',
              'matinais/category/achocolatados-e-cia',
              'matinais/category/aveias-e-cereais',
              'matinais/category/cafes',
              'matinais/category/chas',
              'matinais/category/mel-e-geleias',
              'matinais/category/pastas-e-cremes-doces',
              'matinais/category/torradas',
              'molhos-condimentos-e-conservas/category/alimentos-prontos-e-enlatados',
              'molhos-condimentos-e-conservas/category/conservas',
              'molhos-condimentos-e-conservas/category/maioneses-e-molhos-diversos',
              'molhos-condimentos-e-conservas/category/molhos-de-tomate',
              'molhos-condimentos-e-conservas/category/sopas-e-cremes',
              'molhos-condimentos-e-conservas/category/temperos-e-caldos',
              'padaria/category/bolos-e-tortas',
              'padaria/category/confeitaria',
              'padaria/category/fermentos',
              'padaria/category/paes',
              'pet-shop/category/caes',
              'pet-shop/category/gatos',
              'pet-shop/category/passaros-e-peixes',
              'utensilios-para-o-lar/category/automotivos',
              'utensilios-para-o-lar/category/churrasco',
              'utensilios-para-o-lar/category/conveniencias',
              'utensilios-para-o-lar/category/cozinha',
              'utensilios-para-o-lar/category/embalagens-e-descartaveis',
              'utensilios-para-o-lar/category/jardinagem',
              'utensilios-para-o-lar/category/utensilios-diversos']
departamento = {'Bebidas': ('Bebidas', 'Bebidas Alcoólicas'),
                'Biscoitos, Doces e Matinais': ('Biscoitos e Salgadinhos', 'Doces e Sobremesas', 'Matinais'),
                'Carnes': ('Carnes, Aves e Peixes'),
                'Congelados': ('Congelados e Resfriados'),
                'Hortifruti': ('Feira'),
                'Frios e Laticínios': ('Frios e Laticínios', 'Leites e Iogurtes'),
                'Higiene': ('Higiene e Cuidados Pessoais'),
                'Limpeza': ('Limpeza'),
                'Mercearia': ('Alimentos Básicos', 'Molhos, Condimentos e Conservas'),
                'Padaria': ('Padaria'),
                'Utilidades e Pet': ('Bazar e Utilidades', 'Pet Shop', 'Utensílios para o Lar')}


class RedeconomiaSpider(scrapy.Spider):
    name = "redeconomia"
    start_urls = [
        "https://www.sitemercado.com.br/redeconomiabingen/petropolis-loja-bingen-bingen-r-bingen"]

    def parse(self, response):
        for elemento in range(len(categorias)):
            url = f"https://ecommerce-backend-wl.sitemercado.com.br/api/b2c/product/department/{categorias[elemento]}?store_id=5676"
            headers = {
                "Accept": "application/json, text/plain, */*",
                "Hosturl": "www.sitemercado.com.br",
                "Referer": f"https://www.sitemercado.com.br/redeconomiabingen/petropolis-loja-bingen-bingen-r-bingen/produtos/{referer[elemento]}",
                "Sec-Ch-Ua": "'Google Chrome';v='117', 'Not;A=Brand';v='8', 'Chromium';v='117'",
                "Sec-Ch-Ua-Mobile": "?0",
                "Sec-Ch-Ua-Platform": "Windows",
                "Sm-Token": "{'Location':{'Latitude':-22.505171,'Longitude':-43.182339},'IdClientAddress':0,'IsDelivery':false,'IdLoja':5676,'IdRede':3174,'DateBuild':'2023-09-21T10:23:41.9320414'}",
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
            }
            yield scrapy.Request(url, callback=self.parse_api, headers=headers)

    def parse_api(self, response):
        data = json.loads(response.body)
        product_item = SupermarketItem()

        for product in data['products']:
            if product['price_old'] != 0:
                valor = str(product['department'])
                rotulo = self.encontrar_rotulo(valor, departamento)

                product_item['nome'] = product['excerpt']
                product_item['preco_original'] = product['price_old']
                product_item['preco_oferta'] = product['prices'][0]['price']
                product_item['img_pequena'] = product['image']
                product_item['img_grande'] = product['imageFull']
                product_item['departamento'] = rotulo
                product_item['mercado'] = 'Rede Economia'
                product_item['url'] = 'https://www.sitemercado.com.br/dibsupermercados/petropolis-dib-supermercados-castelanea-r-olavo-bilac/produto/' + product['url']
                product_item['data'] = datetime.date.today()

                yield product_item

    def encontrar_rotulo(self, valor, departamento):
        for rotulo, valores in departamento.items():
            if valor in valores:
                return rotulo
        return None